name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build and Export
        run: |
          npm ci
          npm run build
          npx next export

      - name: Upload static site artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: out/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download static site artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: out/

      - name: Push to AWS S3
        run: |
          aws s3 cp out s3://${{ secrets.APP_BUCKET }} --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"

